# Generated by Django 3.1.5 on 2021-01-14 19:27

import article.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('publications_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True)),
                ('content_preview', models.TextField(blank=True)),
                ('body', tinymce.models.HTMLField(blank=True, null=True)),
                ('image_preview', models.ImageField(blank=True, upload_to=article.models.upload_to)),
                ('image_preview_name', models.CharField(blank=True, max_length=100, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='article.comment')),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='article.article')),
            ],
        ),
    ]
