# Generated by Django 3.1.5 on 2021-01-14 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verification_code', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
